### ISSUE TITLE
Character Directory bug

### ISSUE THREAD

**Issue by Tsybal** [CHOMPStation2/CHOMPStation2#2680]
#### Brief description of the issue

clicked 'character Directory' under OOC tab

#### What you expected to happen

See Character Directory pop up

#### What actually happened

NTOS Blue Screen error message

#### Steps to reproduce
Click Character directory button on OOC tab

#### Code Revision

 Server revision: B:-Using TGS- D:-Using TGS-
Commit: 4a1993aec487fef6e6c0ead7fc3ef193ff82f099
TGS version: 4.11.1
DMAPI version: 5.3.0 

#### Anything else you may wish to add:

NTOS error message: 

- (Location if it's a mapping issue, screenshots, sprites, etc.)
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 TypeError: Unable to get property 'sort' of undefined or null reference
   at d (http://127.0.0.1:50343/tmp14120/tgui.bundle.js:1:118016)
   at Me (http://127.0.0.1:50343/tmp14120/tgui-common.bundle.js:1:173557)
   at Anonymous function (http://127.0.0.1:50343/tmp14120/tgui-common.bundle.js:1:173825)
   at Ae (http://127.0.0.1:50343/tmp14120/tgui-common.bundle.js:1:173803)
   at Pe (http://127.0.0.1:50343/tmp14120/tgui-common.bundle.js:1:174851)
   at Anonymous function (http://127.0.0.1:50343/tmp14120/tgui-common.bundle.js:1:174045)
   at Ae (http://127.0.0.1:50343/tmp14120/tgui-common.bundle.js:1:173913)
   at Ie (http://127.0.0.1:50343/tmp14120/tgui-common.bundle.js:1:174656)
   at Ae (http://127.0.0.1:50343/tmp14120/tgui-common.bundle.js:1:173667)
   at Ie (http://127.0.0.1:50343/tmp14120/tgui-common.bundle.js:1:174656)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"chelkie","interface":"CharacterDirectory","window":{"key":"[0x21091482]-main","size":null,"fancy":1,"locked":0}}

Nanotrasen (c) 2525-2561

**Comment by Tsybal** [comment]
Issue appears to have resolved itself 30 minutes later without any further interference
