### ISSUE TITLE
[UI] TGUI bluescreen when RD console links with nearby machines.

### ISSUE THREAD

**Issue by tacoguy7765093** [CHOMPStation2/CHOMPStation2#8619]
#### Brief description of the bug
Attempting to sync to nearby machines will give a TGUI error, will paste error message here.

#### What you expected to happen
Resync the machines.

#### What actually happened
Bluescreens and never procs through with resynching, closing the window and opening again clears the bluescreen.

#### Steps to reproduce
- (Step 1) Spawn a RD console of any kind
- (Step 2) Attempt to link to nearby devices
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
TypeError: Unable to get property 'linked_lathe' of undefined or null reference
   at d (https://assets.chompstation13.net/c1/asset.c1bb6e9ed596fac1e10d343b37754fb0.js:295:525295)
   at $l (https://assets.chompstation13.net/c1/asset.c1bb6e9ed596fac1e10d343b37754fb0.js:9:65560)
   at Au (https://assets.chompstation13.net/c1/asset.c1bb6e9ed596fac1e10d343b37754fb0.js:9:119158)
   at Iu (https://assets.chompstation13.net/c1/asset.c1bb6e9ed596fac1e10d343b37754fb0.js:9:114795)
   at td (https://assets.chompstation13.net/c1/asset.c1bb6e9ed596fac1e10d343b37754fb0.js:9:114729)
   at bl (https://assets.chompstation13.net/c1/asset.c1bb6e9ed596fac1e10d343b37754fb0.js:9:114582)
   at fc (https://assets.chompstation13.net/c1/asset.c1bb6e9ed596fac1e10d343b37754fb0.js:9:110794)
   at yu (https://assets.chompstation13.net/c1/asset.c1bb6e9ed596fac1e10d343b37754fb0.js:9:109774)
   at b (https://assets.chompstation13.net/c1/asset.c1bb6e9ed596fac1e10d343b37754fb0.js:33:1557)
   at W (https://assets.chompstation13.net/c1/asset.c1bb6e9ed596fac1e10d343b37754fb0.js:33:1924)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0; wbx 1.0.0)
State: {"ckey":"redacted","interface":"ResearchConsole","window":{"key":"[0x202ade1]-main","size":null,"fancy":1,"locked":0}}
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by KotetsuRedwood** [comment]
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/10330701/a0d4abf9-76ed-4643-b29d-18e3e0c799c9)
Happens with deconstruction too - deconstruction still goes through fine though and can also be fixed by just reopening

**Comment by Kashargul** [comment]
Small oversight on type promises, needs to be info && tav
